# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 95abf71fed714f3d0c071ce2a40885a39cd248171324dcfc5b3fe000c31cfe791832d6a0e71272c56c89cf19b762d17f287dae04a70f454f5e70e4b3a9e0c874

test:
  secret_key_base: e40c1eae5a68a002a378642ea03f84afb8ce5c5a676e654ce70c0e300dbd0939385f491103dc103531b6f283dbeebe541e6289ffa45aeb7224ac0d04d6347c85

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
